CREATE TABLE `products` (
	`id` int AUTO_INCREMENT NOT NULL,
	`categoria` varchar(100),
	`instalacao` varchar(100) NOT NULL,
	`familia` varchar(200) NOT NULL,
	`sku` varchar(100) NOT NULL,
	`produto` varchar(500) NOT NULL,
	`moduloLed` text NOT NULL,
	`otica` text NOT NULL,
	`oticaNaoAplicavel` boolean NOT NULL DEFAULT false,
	`holder` text NOT NULL,
	`holderNaoAplicavel` boolean NOT NULL DEFAULT false,
	`dissipador` text NOT NULL,
	`dissipadorNaoAplicavel` boolean NOT NULL DEFAULT false,
	`driverOnoff220` text NOT NULL,
	`driverOnoffBivolt` text NOT NULL,
	`driverDim110v` text,
	`driverDimDali` text,
	`temperaturasCor` text NOT NULL DEFAULT ('["2700","3000","4000","5000"]'),
	`fotoUrl` text,
	`fotoKey` text,
	`custoLuminaria` decimal(10,2),
	`custoDriver` decimal(10,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `products_id` PRIMARY KEY(`id`)
);
